### ISSUE TITLE
"{:0>4}".print("5") is ok, but "{:04}".print("5") is fail

### ISSUE THREAD

**Issue by Silentdoer** [vi-k/format#5]
like title
"{:0>4}".print(5) is ok, but "{:04}".print(5) is ok too

**Comment by vi-k** [comment]
0005 and 0005
and what do you expect?

**Comment by Silentdoer** [comment]
`"{:04}".print("5");` output:5, here should prints 0005 too
but:`"{:0>4}".print("5");` output:0005

**Comment by vi-k** [comment]
Thanks! Fixed in 1.4.0

`"{:04}".print("5")` prints 5000
**For strings, the default alignment is <**

You can test this in python:
print("{:04}".format("5"))

https://playground.programiz.com/

**Comment by vi-k** [comment]
"{:04}".print("5");
prints 5000
For strings, the default alignment is <
