### ISSUE TITLE
"{{" and "}}" are not treated as escape sequences for "{" and "}" 

### ISSUE THREAD

**Issue by dnmorley** [vi-k/format#6]
In [Python](https://en.cppreference.com/w/cpp/utility/format/format) and [C++](https://en.cppreference.com/w/cpp/utility/format/format) `format`, "{{" and "}}" are treated as escape sequences for "{" and "}" .

For example, in Python `"{{0}}->{0}".format(9)` returns `{0}->9`.

However, using this package, `format('{{0}}->{0}', 9)` returns `{9}->9`.

**Comment by vi-k** [comment]
Thanks! I added this
